[package]
name = "pypetal"
version = "0.1.0"
rust-version = "1.85"
edition = "2024"

[lib]
name = "_petal"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.27.1"
petal-decomposition = "0.9"
pyo3 = "0.27"
